name: aigymbuddy
description: "A Flutter Project - PAPB - B"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  carousel_slider: ^5.1.1
  fl_chart: ^1.1.1
  simple_animation_progress_bar: ^1.9.2
  dotted_dashed_line: ^0.0.3
  simple_circular_progress_bar: ^1.0.2
  animated_toggle_switch: ^0.8.5
  readmore: ^3.0.0
  calendar_agenda:
    path: dev_lib/calendar_agenda/

  intl: ^0.20.2
  go_router: ^16.2.4
  shared_preferences: ^2.5.3

  # drift packages for local database
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  path_provider: ^2.1.5

  # sqlite3 packages for web support
  sqlite3: ^2.4.6

  # for better platform support
  sqlite3_web: ^0.3.2

  sqlite3_flutter_libs: ^0.5.0

  # Logging
  logger: ^2.4.0

  path: ^1.9.1
  uuid: ^4.5.1
  provider: ^6.1.5+1
  crypto: ^3.0.6
  cryptography: ^2.7.0
  
  # Secure storage for tokens
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # drift_dev packages for local database
  drift_dev: ^2.29.0
  build_runner: ^2.6.10

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Bold.ttf
        - asset: assets/font/Poppins-Medium.ttf
        - asset: assets/font/Poppins-Regular.ttf
